services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
    command:
      - start-dev
      - --import-realm
      - --log-level=INFO
    volumes:
      - ./import/myrealm-realm.json:/opt/keycloak/data/import/myrealm-realm.json
    ports:
      - "9000:8080"
    container_name: sso-demo-keycloak